version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    #image: nitrozeus1/search-engine-searchloadbalancer:latest
    image: faustis1337/search-engine-searchloadbalancer:${PROMOTED_BUILD}
    ports:
      - 30016:80
  api-search:
    build:
      context: .
      dockerfile: "ApiSearch/Dockerfile"
    #image: nitrozeus1/search-engine-api-search:latest
    image: faustis1337/search-engine-api-search:${PROMOTED_BUILD}
    deploy:
      replicas: 3
    depends_on:
      - load-balancer
  web-ui:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    #image: nitrozeus1/search-engine-frontend:latest
    image: faustis1337/search-engine-frontend:${PROMOTED_BUILD}
    ports:
      - 9023:80